### ISSUE TITLE
Control node via msg not working

### ISSUE THREAD

**Issue by dvyjns** [bartbutenaers/node-red-contrib-msg-speed#12]
Hello,

I am attempting to use 'msg.speed_reset = true' to reset all my speed measurements to 0 and start measuring all over again but I can not get it to work. I copy/pasted your example into a new flow and ran it in debug mode but the Reset/Resume/Pause buttons are not working in the example flow either. Whenever I press 'Reset' it increases the value by 1 rather than resetting it.  Any suggestions?

Thank you,

**Comment by bartbutenaers** [comment]
Hi @dvyjns,

I have installed the latest version from NPM, and then it all works fine for me:

![msg_speed_demo_control](https://user-images.githubusercontent.com/14224149/105612495-d5f88180-5dbc-11eb-90d5-06618a069de8.gif)

When I cannot reproduce the problem, it is very hard to find the root cause ...
Are you sure you have the latest ***2.0.0*** version of my node?  
You can find the version via the Node-RED "Manage palette" menu:

![image](https://user-images.githubusercontent.com/14224149/105612578-620aa900-5dbd-11eb-94db-62520f33dc3f.png)

In case you want to share your demo, you can e.g. record your screen via [gifcam](http://blog.bahraniapps.com/gifcam/) ...

Bart

**Comment by dvyjns** [comment]
Thank you for the quick reply, very much appreciated! It turns out I was running version 1.0.0. Once I updated to the latest 2.0.0 version of the node everything started working as expected. 

I am using the node to keep track of efficiency on a packaging line (last 1 min. effeciency, last 1 hour efficiency, etc..) So far it's working great, especially now that I can reset the gauges properly. Thanks again.

**Comment by bartbutenaers** [comment]
Thanks for the feedback!
