### ISSUE TITLE
Combine original input message

### ISSUE THREAD

**Issue by romprod** [bartbutenaers/node-red-contrib-msg-speed#16]
Hi, is it possible to combine\merge the original message with the timer counts so that all information is contained in a single message?

The original message could be moved to something like msg.original.payload or something similar

**Comment by bartbutenaers** [comment]
Hi @romprod,

Unfortunately that is possible with the current [design](https://github.com/node-red/designs/discussions/67) of this node.   You can read through that (very technical document) if you would like to know the reason why...  But to summarize: to speed up calculations, this node at the end subtract two numbers.  So there is no way you can calculate the speed at any moment when a message arrives, to store the speed info into every message.

If you would like to do something like that, I assume a moving window might be much better.  But that would require a completely different node to be implemented from scratch.

Since I cannot solve that in this node, I am going to close this isse.

Kind regards,
Bart
