### ISSUE TITLE
Make the interval more configurable

### ISSUE THREAD

**Issue by boldt** [bartbutenaers/node-red-contrib-msg-speed#6]
Right now, the interval is only 1/s, 1/min or 1/h.
It would good to have an additional field to enter a number to create intervals like 30/s, 125/s, 5/min, 15/min, ...

**Comment by bartbutenaers** [comment]
Hi Dennis,

I have implemented your feature request as version _**0.1.0**_ on this Github repository.  
Would be nice if you could test it, before I publish it on NPM.   
You can install it directly from Github, using this command from your Node-RED folder (e.g. cd $HOME/.node-red):
```
npm install bartbutenaers/node-red-contrib-msg-speed
```

I have added an extra interval length input field in the "Frequency" row, where you need to enter a number ( > 0 and default 1):

![image](https://user-images.githubusercontent.com/14224149/86832639-b73cd280-c098-11ea-8648-b2705f4bd839.png)

But I have couple of questions:

1. I'm not sure how the node status should look like.  Currently I show it like this:

   ![image](https://user-images.githubusercontent.com/14224149/86833136-68dc0380-c099-11ea-9ef7-d8d09b88de8d.png)

   But not sure if that format is readable enough.  Can be `123/4hour` or `123 / 4hour` or `123 / 4 hour` or ...  
   Personally I prefer `123 / 4 hour` because it has spaces between all parts. 

   P.S. if people use a Status-node to monitor this Speed-node status, then I will break existing flows ;-(

2. I'm also not sure whether I should report  `123 / 1 hour` or simply `123 / hour` in case the interval is `1` long?

3. Instead of measuring the speed per 30 seconds, one could also measure the speed per minute and divide it afterwards by two.  Do you have any particular use case, which I can use on my readme page to explain why it is better to use 30 seconds.  
   + To avoid extra nodes in your flow
   + To make the startup interval shorter
   + Other reasons?

Kind regards,
Bart

**Comment by boldt** [comment]
Hey Bart,

that was quick, awesome! I'll run a test of that version tomorrow.

1. I also prefer the space version, e.g. `123 / 4 hour`. In latex you usually use `\;` to separate the numer and the unit. what do you think about using the [narrow no-break space](https://stackoverflow.com/questions/8515365/are-there-other-whitespace-codes-like-nbsp-for-half-spaces-em-spaces-en-space) as well, e.g. `123 / 4 hour`? 
    * What excalty is breaking the existings flows? I don't get it...
2. `123 / 1 hour` would be consitent, but `123 / hour` looks better.
3. In our use case, we have pulse signals for the cycles of our machines. But we have a lot of different different cycle times, i.e., from 5s to 5min. With a "sliding windows" of 10/15 min I want to normalize the interval for all machines. Like this, we'll be able to see the speed of all machines within the last 10/15 minutes.

Regards Dennis

**Comment by bartbutenaers** [comment]
Morning Dennis,
+ What do you mean with *"using the narrow no-break space as well"*.  With *"as well"* do you mean that the status text should customizable somehow (to offer multiple ways to present it)?  Or are you talking about the output message?  In the output message I currently send `msg.frequency` values like `15 min` .   But instead I could also use 2 separate output fields like `msg.frequency` which contains `min` and a new `msg.interval` field which contains `15`, so you don't need to split them in your flow.  And I could add a new field `msg.status` (or another name) which contains the complete status text `15 min`.
+ With break existing flows I mean this: lots of people use the Status node, to detect changes in the status text of the node.  If somebody uses a status node to read my old status `15/min` then they will now get `15/ 1 min` as output message on their status node.  So their flow will probably not work correctly anymore ...
+ Thanks for your example!!  

Now off to work ...

**Comment by boldt** [comment]
Good moring,

* With "as well" I meant, as it is done in Latex usally. 
* I think, we should try to ensure, that is stays backward compatible, e.g. everyone updating the package should not see a difference. So if the frequency is 1, it should stay `1/min`
* Adding further infos like `msg.status` doesn't hurt anybody

I just installed your version from github. After a restart of nodered I get the following error:

![2020-07-08 09_37_33-Node-RED _ hskiot1-srv](https://user-images.githubusercontent.com/750793/86891567-572d4700-c0ff-11ea-9c37-48876a4e0134.png)

I have to open every speed node and save it once. This should not happen to existing flows.

Also when I try to deploy the flow, it showd me warning (here in German):

![grafik](https://user-images.githubusercontent.com/750793/86891933-d9b60680-c0ff-11ea-80ea-997f6110e4b3.png)

**Comment by bartbutenaers** [comment]
+ if the frequency is 1, it should stay 1/min --> I agree
+ Adding further infos like msg.status doesn't hurt anybody --> I agree.  So I will change the output message to contain following fields:
   + `msg.frequency`: e.g. "min"
   + `msg.interval`: e.g. "15"
   + `msg.int_and_freq`: e.g. "15 min"
+ I have to open every speed node and save it once. --> That is weird.  I had added migration code, to make sure this wouldn't happen.  Will need to debug that tonight, because seems to be a bug ...
+ when I try to deploy the flow, it showd me warning --> Does that warning also appears after you have manually opened every speed node config screen.  Or is that warning only about the speed nodes that you have not openend yet?
+ as it is done in Latex usally --> I have no knowledge about Laxec (or narrow no breaks) or related things.  I should make sure that it works fine for everybody, which means I will use normal spaces (to avoid that everybody needs to start reading about it).  Could you explain in simple words why a normal space is not sufficient for you in your Node-RED flow, and why you prefer the narrow no-breaks you are referring to?  Because I have very limited free time to digg into that topic unfortunately ...  But I need to make sure that it is easy understandable and usable for everybody.

**Comment by boldt** [comment]
* The warning only appeared for all speed nodes, which I didnt update yet. After I updates all, the warning disappeared
* Lets keep the normal space and its totally fine :)

[EDIT]

> Note that the rule doesn't specify how wide the space should be. Some references recommend a normal inter-word space, while others recommend a thin space. In any case, the space is nonbreakable.

A non breakable space would be good. If it's thin or not, it doesn't matter.

https://english.stackexchange.com/questions/2794/punctuation-with-units

**Comment by bartbutenaers** [comment]
The validation problem (red triangle) should be solved now: fixed on Github.  Will do the remaining this evening.  Lunch break is over ...

**Comment by boldt** [comment]
Sounds good.

**Comment by bartbutenaers** [comment]
I hope everything is fine now on Github.  
+ If you have a flow with old speed-nodes, you shouldn't get an error anymore (red triangle).
+ The node status now contains spaces:

   ![image](https://user-images.githubusercontent.com/14224149/86941149-e8261180-c143-11ea-9ca8-26c25a6ca5bb.png)

+ When the interval is `1` then it is not displayed in the node status:

   ![image](https://user-images.githubusercontent.com/14224149/86941063-c7f65280-c143-11ea-84c0-c8e2ffbc9632.png)

+ The output message contains the following information:

   ![image](https://user-images.githubusercontent.com/14224149/86941295-13a8fc00-c144-11ea-9ce2-77c255766aaa.png)

   Note that the interval is always included in the `msg.intervalAndFrequency` (even if it has value `1`), since the name of the field promises that both interval _**AND**_ frequency will be included:

   ![image](https://user-images.githubusercontent.com/14224149/86941542-5b2f8800-c144-11ea-9738-00660892c39b.png)

Hopefully it is now useful in real life, like in your case ...

**Comment by bartbutenaers** [comment]
P.S. Currently this node sends an output message every second.  Do you think - based on your experience - it would be useful to have an adjustable output message frequency, e.g. an output message every 20 second?

**Comment by bartbutenaers** [comment]
@boldt ,
Any updates on this?

**Comment by bartbutenaers** [comment]
@boldt ,
Any updates on this?

**Comment by bartbutenaers** [comment]
For anybody following this discussion: this feature has now been published as version ***1.0.0*** on NPM.
