### ISSUE TITLE
User Question

### ISSUE THREAD

**Issue by cllatser** [bartbutenaers/node-red-contrib-msg-speed#8]
Good morning, thanks for creating this great node. Is there any way to stop it by sending some kind of message to the node? Or once it's activated, you can't stop it?

Thank you very much.

**Comment by bartbutenaers** [comment]
Hi @cllatser,

I have build - about two years ago - some message control in the "msg-control" branch, as you can see on the  [readme](https://github.com/bartbutenaers/node-red-contrib-msg-speed/tree/msg-control#control-node-via-msg----since-version-010) page of that branch.  Is that what you are looking for?

That functionality has never been published on npm.  To be honest, I don't even know why I have never done that.  Don't even know anymore whether it has been tested 100%...

If you want to experiment with it, you can install that branch from within your .node-red folder:
```
npm install bartbutenaers/node-red-contrib-msg-speed#msg-control
```
Would be nice to get some feedback about it!
Bart

**Comment by cllatser** [comment]
Thanks a lot. I will try it. 😄👍🏻

**Comment by bartbutenaers** [comment]
No no, please don't close this issue :-)
That branch is outdated: it contains message control, but all other new features - which have been added to this node the last two years - are not available in that branch...
If you would have some time to test it and report about it, we could merge afterwards that branch (into the master branch) and publish it on NPM.  Then it becomes available in the Node-RED "manage palette" menu for all users...
Thanks!

**Comment by bartbutenaers** [comment]
Hi @cllatser,
I have reworked the speed node.  The *"master"* branch is now up-to-date and the *"msg_control"* branch has been removed.
You can find more information about it on the Node-RED [forum](https://discourse.nodered.org/t/announce-node-red-contrib-msg-speed-1-0-0-request-for-testers/38160).
Would be nice if you could give me some feedback.  Would like to publish this new version on NPM as soon as possible.
Bart

**Comment by cllatser** [comment]
Perfect, give me a few days and I'll give it a try. Thank you.

**Comment by bartbutenaers** [comment]
Closing this issue since that version is published on npm already on 06/01/2020...
